# Generated by Django 4.0.3 on 2022-03-27 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=35)),
                ('short_name', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('call_name', models.CharField(max_length=20)),
                ('long', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('service_status', models.CharField(max_length=12)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transit.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('long', models.IntegerField()),
                ('lat', models.IntegerField()),
                ('code', models.IntegerField()),
                ('routes', models.ManyToManyField(to='transit.route')),
            ],
        ),
    ]
