# Generated by Django 4.0.3 on 2022-03-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='threshold_eta',
            new_name='start',
        ),
    ]
