# Generated by Django 3.2.12 on 2022-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_alter_usersettings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='long',
            field=models.FloatField(),
        ),
    ]
