# Generated by Django 3.2.12 on 2022-03-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_auto_20220327_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='fav_stop',
            field=models.ForeignKey(blank=True, default=4266820, on_delete=django.db.models.deletion.DO_NOTHING, to='transit.stop'),
        ),
    ]
