# Generated by Django 3.2.12 on 2022-03-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_rename_threshold_eta_usersettings_start'),
        ('transit', '0006_usersettings_fav_stop'),
    ]

    operations = [
    ]
